USE elixo;

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS telefone VARCHAR(20) NULL AFTER senha,
  ADD COLUMN IF NOT EXISTS data_nascimento DATE NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(10) NULL AFTER data_nascimento,
  ADD COLUMN IF NOT EXISTS rua VARCHAR(120) NULL AFTER cep,
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL AFTER rua,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL AFTER numero,
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100) NULL AFTER bairro,
  ADD COLUMN IF NOT EXISTS estado CHAR(2) NULL AFTER cidade,
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(120) NULL AFTER estado;
